version: '3'

services:
  
  # DATABASE
    db:
      container_name: "DockerWP-db"
      image: mysql:5.7  
      restart: always
      volumes:
        - ./db_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: password  
        MYSQL_DATABASE: wp-docker
        MYSQL_USER: wp-docker
        MYSQL_PASSWORD: wp-docker
      networks:
        - dockerwpsites
  
  # PHPMYADMIN
    phpmyadmin:
      depends_on:
        - db
      container_name: DockerWP-PHPMYADMIN
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
      - '12001:80'
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: password
      networks:
        - dockerwpsites
  
  # WORDPRESS
    wordpress:
      depends_on: 
        - db
      image: wordpress:latest
      restart: always
      ports:
        - '13001:80'
      volumes: ['/var/www/html'] 
      container_name: "DockerWP-WORDPRESS"
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wp-docker
        WORDPRESS_DB_PASSWORD: wp-docker   
        WORDPRESS_DB_NAME: wp-docker 
      networks:
        - dockerwpsites         

networks:
  dockerwpsites:
volumes:
  db_data: 


 

